title: Interoperabilidad MINSAL
description: Página oficial de documentación de los proyectos de interoperabilidad MINSAL-CL
#theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
url: https://minsal-cl.github.io/

logo: "/assets/images/MINSAL.png"

favicon_ico: "/assets/images/gob_favicon.ico"

color_scheme: light



# Aplica valores por defecto a archivos .md
defaults:
  # EJEMPLO: ocultar del menú todo lo que esté en la carpeta NID
  - scope:
      path: "fhir/ig"     # <-- aquí pones la carpeta donde están esos 100 md
      type: "pages"   # páginas normales
    values:
      nav_exclude: true


#---
#layout: default
#title: Especificacion de la Arquitectura
#nav_order: 2
#has_children: true
#---
#layout: default
#title: Componentes de la Arquitectura
#nav_order: 3
#has_children: true
#---
